// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses_write.sql

package coursesdb

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses
(slug, title, price)
VALUES (?, ?, ?)
RETURNING id
`

type CreateCourseParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (int64, error) {
	row := q.queryRow(ctx, q.createCourseStmt, createCourse, arg.Slug, arg.Title, arg.Price)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateCoursePrice = `-- name: UpdateCoursePrice :one
UPDATE courses
SET price = ?
WHERE id = ?
RETURNING id, slug, title, price
`

type UpdateCoursePriceParams struct {
	Price int64 `json:"price"`
	ID    int64 `json:"id"`
}

func (q *Queries) UpdateCoursePrice(ctx context.Context, arg UpdateCoursePriceParams) (Course, error) {
	row := q.queryRow(ctx, q.updateCoursePriceStmt, updateCoursePrice, arg.Price, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}
