// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses_read.sql

package coursesdb

import (
	"context"
	"strings"
)

const findCourseByID = `-- name: FindCourseByID :one
SELECT id, slug, title, price
FROM courses
WHERE id = ?
`

func (q *Queries) FindCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.queryRow(ctx, q.findCourseByIDStmt, findCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const findCoursesByIDs = `-- name: FindCoursesByIDs :many
SELECT id, slug, title, price
FROM courses
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) FindCoursesByIDs(ctx context.Context, ids []int64) ([]Course, error) {
	query := findCoursesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, title, price
FROM courses
LIMIT ? OFFSET ?
`

type ListCoursesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.query(ctx, q.listCoursesStmt, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByMaxPrice = `-- name: ListCoursesByMaxPrice :many
SELECT id, slug, title, price
FROM courses
WHERE price <= ?
`

func (q *Queries) ListCoursesByMaxPrice(ctx context.Context, price int64) ([]Course, error) {
	rows, err := q.query(ctx, q.listCoursesByMaxPriceStmt, listCoursesByMaxPrice, price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
