// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coursesdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createCourseStmt, err = db.PrepareContext(ctx, createCourse); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCourse: %w", err)
	}
	if q.findCourseByIDStmt, err = db.PrepareContext(ctx, findCourseByID); err != nil {
		return nil, fmt.Errorf("error preparing query FindCourseByID: %w", err)
	}
	if q.findCoursesByIDsStmt, err = db.PrepareContext(ctx, findCoursesByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query FindCoursesByIDs: %w", err)
	}
	if q.listCoursesStmt, err = db.PrepareContext(ctx, listCourses); err != nil {
		return nil, fmt.Errorf("error preparing query ListCourses: %w", err)
	}
	if q.listCoursesByMaxPriceStmt, err = db.PrepareContext(ctx, listCoursesByMaxPrice); err != nil {
		return nil, fmt.Errorf("error preparing query ListCoursesByMaxPrice: %w", err)
	}
	if q.updateCoursePriceStmt, err = db.PrepareContext(ctx, updateCoursePrice); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCoursePrice: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createCourseStmt != nil {
		if cerr := q.createCourseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCourseStmt: %w", cerr)
		}
	}
	if q.findCourseByIDStmt != nil {
		if cerr := q.findCourseByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findCourseByIDStmt: %w", cerr)
		}
	}
	if q.findCoursesByIDsStmt != nil {
		if cerr := q.findCoursesByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findCoursesByIDsStmt: %w", cerr)
		}
	}
	if q.listCoursesStmt != nil {
		if cerr := q.listCoursesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCoursesStmt: %w", cerr)
		}
	}
	if q.listCoursesByMaxPriceStmt != nil {
		if cerr := q.listCoursesByMaxPriceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCoursesByMaxPriceStmt: %w", cerr)
		}
	}
	if q.updateCoursePriceStmt != nil {
		if cerr := q.updateCoursePriceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCoursePriceStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	createCourseStmt          *sql.Stmt
	findCourseByIDStmt        *sql.Stmt
	findCoursesByIDsStmt      *sql.Stmt
	listCoursesStmt           *sql.Stmt
	listCoursesByMaxPriceStmt *sql.Stmt
	updateCoursePriceStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		createCourseStmt:          q.createCourseStmt,
		findCourseByIDStmt:        q.findCourseByIDStmt,
		findCoursesByIDsStmt:      q.findCoursesByIDsStmt,
		listCoursesStmt:           q.listCoursesStmt,
		listCoursesByMaxPriceStmt: q.listCoursesByMaxPriceStmt,
		updateCoursePriceStmt:     q.updateCoursePriceStmt,
	}
}
