// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coursesdb

type Course struct {
	ID    int64  `json:"id"`
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}
