// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coursesdb

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (int64, error)
	FindCourseByID(ctx context.Context, id int64) (Course, error)
	FindCoursesByIDs(ctx context.Context, ids []int64) ([]Course, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListCoursesByMaxPrice(ctx context.Context, price int64) ([]Course, error)
	UpdateCoursePrice(ctx context.Context, arg UpdateCoursePriceParams) (Course, error)
}

var _ Querier = (*Queries)(nil)
