CREATE TABLE IF NOT EXISTS course_members(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER REFERENCES users(id),
  course_id INTEGER REFERENCES courses(id),
  joined_at DATETIME DEFAULT CURRENT_TIMESTAMP
);