// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_members_read.sql

package coursemembersdb

import (
	"context"
	"database/sql"
)

const getCourseWithMembers = `-- name: GetCourseWithMembers :one
WITH members AS (
  SELECT
    cm.course_id,
    cm.user_id,
    cm.joined_at
  FROM course_members AS cm
  WHERE cm.course_id = ?1
)
SELECT
  c.id AS course_id,
  c.slug AS course_slug,
  c.title AS course_title,
  c.price AS course_price,
  COALESCE(
    json_group_array(
      json_object(
        'id', u.id,
        'email', u.email,
        'name', u.name,
        'age', u.age
      )
    ) FILTER (WHERE u.id IS NOT NULL),
    json('[]')
  ) AS members
FROM courses AS c
LEFT JOIN members AS m ON c.id = m.course_id
LEFT JOIN users AS u ON u.id = m.user_id
WHERE c.id = ?1
`

type GetCourseWithMembersRow struct {
	CourseID    int64       `json:"course_id"`
	CourseSlug  string      `json:"course_slug"`
	CourseTitle string      `json:"course_title"`
	CoursePrice int64       `json:"course_price"`
	Members     interface{} `json:"members"`
}

func (q *Queries) GetCourseWithMembers(ctx context.Context, id int64) (GetCourseWithMembersRow, error) {
	row := q.queryRow(ctx, q.getCourseWithMembersStmt, getCourseWithMembers, id)
	var i GetCourseWithMembersRow
	err := row.Scan(
		&i.CourseID,
		&i.CourseSlug,
		&i.CourseTitle,
		&i.CoursePrice,
		&i.Members,
	)
	return i, err
}

const getUserByCourseMemberID = `-- name: GetUserByCourseMemberID :one
SELECT
  cm.id AS course_member_id,
  u.id AS user_id,
  u.email AS user_email,
  u.name AS user_name,
  u.age AS user_age
FROM course_members AS cm
LEFT JOIN users AS u ON cm.user_id = u.id
WHERE cm.id = ?
`

type GetUserByCourseMemberIDRow struct {
	CourseMemberID int64          `json:"course_member_id"`
	UserID         sql.NullInt64  `json:"user_id"`
	UserEmail      sql.NullString `json:"user_email"`
	UserName       sql.NullString `json:"user_name"`
	UserAge        sql.NullInt64  `json:"user_age"`
}

func (q *Queries) GetUserByCourseMemberID(ctx context.Context, id int64) (GetUserByCourseMemberIDRow, error) {
	row := q.queryRow(ctx, q.getUserByCourseMemberIDStmt, getUserByCourseMemberID, id)
	var i GetUserByCourseMemberIDRow
	err := row.Scan(
		&i.CourseMemberID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.UserAge,
	)
	return i, err
}
