// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_members_write.sql

package coursemembersdb

import (
	"context"
	"database/sql"
)

const createCourseMember = `-- name: CreateCourseMember :exec
INSERT INTO course_members
(user_id, course_id)
VALUES (?, ?)
`

type CreateCourseMemberParams struct {
	UserID   sql.NullInt64 `json:"user_id"`
	CourseID sql.NullInt64 `json:"course_id"`
}

func (q *Queries) CreateCourseMember(ctx context.Context, arg CreateCourseMemberParams) error {
	_, err := q.exec(ctx, q.createCourseMemberStmt, createCourseMember, arg.UserID, arg.CourseID)
	return err
}
