// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coursemembersdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createCourseMemberStmt, err = db.PrepareContext(ctx, createCourseMember); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCourseMember: %w", err)
	}
	if q.getCourseWithMembersStmt, err = db.PrepareContext(ctx, getCourseWithMembers); err != nil {
		return nil, fmt.Errorf("error preparing query GetCourseWithMembers: %w", err)
	}
	if q.getUserByCourseMemberIDStmt, err = db.PrepareContext(ctx, getUserByCourseMemberID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByCourseMemberID: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createCourseMemberStmt != nil {
		if cerr := q.createCourseMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCourseMemberStmt: %w", cerr)
		}
	}
	if q.getCourseWithMembersStmt != nil {
		if cerr := q.getCourseWithMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCourseWithMembersStmt: %w", cerr)
		}
	}
	if q.getUserByCourseMemberIDStmt != nil {
		if cerr := q.getUserByCourseMemberIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByCourseMemberIDStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	createCourseMemberStmt      *sql.Stmt
	getCourseWithMembersStmt    *sql.Stmt
	getUserByCourseMemberIDStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		createCourseMemberStmt:      q.createCourseMemberStmt,
		getCourseWithMembersStmt:    q.getCourseWithMembersStmt,
		getUserByCourseMemberIDStmt: q.getUserByCourseMemberIDStmt,
	}
}
