// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coursemembersdb

import (
	"context"
)

type Querier interface {
	CreateCourseMember(ctx context.Context, arg CreateCourseMemberParams) error
	GetCourseWithMembers(ctx context.Context, id int64) (GetCourseWithMembersRow, error)
	GetUserByCourseMemberID(ctx context.Context, id int64) (GetUserByCourseMemberIDRow, error)
}

var _ Querier = (*Queries)(nil)
