// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders_read.sql

package ordersdb

import (
	"context"
	"database/sql"
)

const getUserByOrderID = `-- name: GetUserByOrderID :one
SELECT
  o.id AS order_id,
  u.id AS user_id,
  u.email AS user_email,
  u.name AS user_name,
  u.age AS user_age
FROM orders AS o
LEFT JOIN users AS u ON o.user_id = u.id
WHERE o.id = ?
`

type GetUserByOrderIDRow struct {
	OrderID   int64          `json:"order_id"`
	UserID    sql.NullInt64  `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	UserName  sql.NullString `json:"user_name"`
	UserAge   sql.NullInt64  `json:"user_age"`
}

func (q *Queries) GetUserByOrderID(ctx context.Context, id int64) (GetUserByOrderIDRow, error) {
	row := q.queryRow(ctx, q.getUserByOrderIDStmt, getUserByOrderID, id)
	var i GetUserByOrderIDRow
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.UserAge,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT
  o.id AS order_id,
  o.amount_cents AS order_amount_cents,
  o.created_at AS order_created_at,
  u.id AS user_id,
  u.email AS user_email,
  u.name AS user_name,
  u.age AS user_age,
  c.id AS course_id,
  c.slug AS course_slug,
  c.title AS course_title,
  c.price AS course_price
FROM orders AS o
LEFT JOIN users AS u ON o.user_id = u.id
LEFT JOIN courses AS c ON o.course_id = c.id
ORDER BY o.created_at DESC
LIMIT ? OFFSET ?
`

type ListOrdersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListOrdersRow struct {
	OrderID          int64          `json:"order_id"`
	OrderAmountCents int64          `json:"order_amount_cents"`
	OrderCreatedAt   sql.NullTime   `json:"order_created_at"`
	UserID           sql.NullInt64  `json:"user_id"`
	UserEmail        sql.NullString `json:"user_email"`
	UserName         sql.NullString `json:"user_name"`
	UserAge          sql.NullInt64  `json:"user_age"`
	CourseID         sql.NullInt64  `json:"course_id"`
	CourseSlug       sql.NullString `json:"course_slug"`
	CourseTitle      sql.NullString `json:"course_title"`
	CoursePrice      sql.NullInt64  `json:"course_price"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.query(ctx, q.listOrdersStmt, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderAmountCents,
			&i.OrderCreatedAt,
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.UserAge,
			&i.CourseID,
			&i.CourseSlug,
			&i.CourseTitle,
			&i.CoursePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
