// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders_write.sql

package ordersdb

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders
(user_id, course_id, amount_cents)
VALUES (?, ?, ?)
`

type CreateOrderParams struct {
	UserID      sql.NullInt64 `json:"user_id"`
	CourseID    sql.NullInt64 `json:"course_id"`
	AmountCents int64         `json:"amount_cents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.exec(ctx, q.createOrderStmt, createOrder, arg.UserID, arg.CourseID, arg.AmountCents)
	return err
}
