// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ordersdb

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	GetUserByOrderID(ctx context.Context, id int64) (GetUserByOrderIDRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
}

var _ Querier = (*Queries)(nil)
