// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	Age       sql.NullInt64  `json:"age"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
