// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteUser(ctx context.Context, id int64) error
	FindUserByID(ctx context.Context, id int64) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
