// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_write.sql

package usersdb

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(email, name, age)
VALUES (?, ?, ?)
RETURNING id
`

type CreateUserParams struct {
	Email string         `json:"email"`
	Name  sql.NullString `json:"name"`
	Age   sql.NullInt64  `json:"age"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.Name, arg.Age)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = COALESCE(?1, email),
  name = COALESCE(?2, name),
  age = COALESCE(?3, age)
WHERE id = ?4
RETURNING id, email, name, age, created_at
`

type UpdateUserParams struct {
	Email sql.NullString `json:"email"`
	Name  sql.NullString `json:"name"`
	Age   sql.NullInt64  `json:"age"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}
